# theme.toml for the Airspace Hugo theme

name = "Smart Farmers Hub"
license = "CC BY 3.0"
licenselink = "https://creativecommons.org/licenses/by/3.0/"
description = "Hugo port of the Themefisher’s Airspace theme"
homepage = "https://www.smartfarmershub.com/"
tags = ["blog",'google-analytics', 'fast', 'modern', 'minimal', 'minimalistic', 'business', 'agency-template', 'white', 'light', 'multilingual', "bootstrap", "company", "portfolio", "projects", "responsive", "themefisher"]
features = ["blog", "company", "responsive", "seo-friendly"]
min_version = "0.64.0"

[author]
  name = "Smart Farmers Hub"
  homepage = "https://www.smartfarmershub.com/"

[original]
  name = "Airspace"
  homepage = "https://themefisher.com/products/airspace-free-bootstrap-website-template/"
  repo = "https://github.com/themefisher/airspace-free-html5-agency-template"
